spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:8066/u_03_jdjc
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 8080
